### PR TITLE
call soup.find_all only once in backcompat.apply_rules

### PR DESCRIPTION
**Pull request by kylewm**
22 calls to soup.find_all turned out to be very expensive, taking ~90%
of the total time spent parsing. instead we can just call it once and
collect all the classic microformats roots at once.

cc: @snarfed @KevinMarks

### CODE REVIEW

**Comment by snarfed** [comment]
woo awesome! thanks @kylewm!

i take it that 90% was from light benchmarking?

**Comment by kylewm** [comment]
yes to light benchmarking. I profiled the parser while processing a few different pages, and eyeballed the amount of time spent on apply_rules compared to everything else.

**Comment by kevinmarks** [comment]
empirically this has mostly sped up parsing in mf2py on my hovertest page:
url time before time after
http://about.me/thisisdeb 3.69 2.11 57%
http://cascadesf.com/ 13.62 5.43 40%
http://chocolateandvodka.com/ 14.61 11.73 80%
http://epeus.blogspot.com 11.24 6.72 60%
http://giudici.us/ 0.425 1.22 287%
http://kathyems.wordpress.com/ 24.92 9.13 37%
http://kevinmarks.com 2.63 5.06 192%
http://known.kevinmarks.com 9.13 4.43 49%
http://laurelschwulst.com/ 1.74 2.31 133%
http://ma.tt 1.61 4.64 288%
http://pmckay.com 0.431 1.73 401%
http://rickydesign.me/ 5.13 1.33 26%
http://tantek.com 3.43 4.45 130%
http://twitter.com/kevinmarks 5.53 2.32 42%
http://werd.io 11.75 12.11 103%
http://www.katiejohnson.me/whatimthinking.html 31.34 10.53 34%
https://kylewm.com/ 40.2 9.62 24%
https://plus.google.com/+KevinMarks 1.35 1.62 120%
https://snarfed.org/ 16.68 5.31 32%

**Comment by snarfed** [comment]
bridgy saw this speed up its mf2py parse times an average (mean) 3-5x during a 4h test run just now. woo!

**Comment by snarfed** [comment]
friendly nudge @tommorris. itching to see this get released so i can use it properly instead of hackily. :P

**Comment by tommorris** [comment]
Away from laptop for the next ~12 hours but will take a look tomorrow. I am as excited by the performance improvents!

-- 
Tom Morris
<http://tommorris.org/>

**Comment by kylewm** [comment]
@tommorris OK with you if @snarfed or @Kevinmarks reviews, and I merge and upload a new pypi package pending their approval?

**Comment by tommorris** [comment]
Go for it @kylewm.

-- 
Tom Morris
<http://tommorris.org/>

**Comment by snarfed** [comment]
i'm not familiar with mf2py, but this lgtm! more importantly, mf2py has backcompat tests which (i assume :P) pass, and bridgy and granary's do too.

**Comment by kylewm** [comment]
1.0.3 is up here https://pypi.python.org/pypi/mf2py/1.0.3

thanks all

**Comment by snarfed** [comment]
yay, thank you!

**Pull request merged**
