### PR TITLE
implied properties should ignore alt=""

### LINKED ISSUE #67: img alt="" blocks implied name property
This html

```html
<a class="h-card" href="https://twitter.com/kylewmahan">
  <img src="https://pbs.twimg.com/profile_images/641457114381074432/vUdKopH8.jpg" alt="">
  @kylewmahan
</a>
```
gives

```json

{"items": [{"properties": {"name": [""],
                           "photo": ["https://pbs.twimg.com/profile_images/641457114381074432/vUdKopH8.jpg"],
                           "url": ["https://twitter.com/kylewmahan"]},
            "type": ["h-card"]}],
 "rel-urls": {},
 "rels": {}}
```

Specifically "name" is blank, where I think it should be "@kylewmahan"

### PR DESCRIPTION
**Pull request by kylewm**
Based on discussion in http://microformats.org/wiki/microformats2-parsing-issues#implied_name_when_alt.3D.22.22
the implied cases that expect alt or title should ignore it when it's intentionally blank.

Fixes #67

### CODE REVIEW

**Comment by tommorris** [comment]
Thanks for the contribution, @kylewm.

My only real concern with it is that if the behaviour of `alt` attribute handling changes simply by changing all the `if prop_value is not None` expressions into `if prop_value`, then mf2py isn't handling the case of an empty valued string explicitly.

What do we do if we have a string that is just whitespace? `alt="    "`, say? Do we want to run a `str.strip` on it? I just think relying on Python's object comparison logic to handle this is something we can avoid in order to better fit with "Explicit is better than implicit" in [PEP20](https://www.python.org/dev/peps/pep-0020/).

Otherwise, :+1:

**Comment by kylewm** [comment]
That's a fair point. And I'm realizing that for some (src and href), "" is a totally valid/meaningful value. OK I'll rework this a bit.

To the specific example of `alt=" "`, I don't think we'd consider that empty the same way `alt=""` is empty. I wouldn't want to widen the `alt=""` exception [being proposed](http://microformats.org/wiki/microformats2-parsing-issues#implied_name_when_alt.3D.22.22)

**Comment by kylewm** [comment]
Does this look better?

**Comment by tommorris** [comment]
Excellent stuff, @kylewm. :+1:

**Comment by kylewm** [comment]
Thanks so much for reviewng Tom!

**Pull request merged**
