### PR TITLE
unicode normalisation, backcompat fixes, new test harness, new rel parsing

### PR DESCRIPTION
**Pull request by kevinmarks**
possibly that is too much for one pull request?

Also the test harness should probably point to the microformats repository, not my fork

### CODE REVIEW

**Comment by kylewm** [comment]
This looks pretty good to me. Is it OK with you if I merge it and then move the testsuite test runner from test_parser.py to test_suite.py, so they can be excluded from Travis-CI for now?

**Comment by kevinmarks** [comment]
sounds good to me - we can always split the test runner by subdirectory
later.

**Comment by kylewm** [comment]
running locally, I'm getting these warnings. Any idea what that's about?
```
/home/kmahan/.virtualenvs/mf2py/local/lib/python2.7/site-packages/bs4/dammit.py:269: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if (len(data) >= 4) and (data[:2] == b'\xfe\xff') \
/home/kmahan/.virtualenvs/mf2py/local/lib/python2.7/site-packages/bs4/dammit.py:273: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif (len(data) >= 4) and (data[:2] == b'\xff\xfe') \
/home/kmahan/.virtualenvs/mf2py/local/lib/python2.7/site-packages/bs4/dammit.py:277: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif data[:3] == b'\xef\xbb\xbf':
/home/kmahan/.virtualenvs/mf2py/local/lib/python2.7/site-packages/bs4/dammit.py:280: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif data[:4] == b'\x00\x00\xfe\xff':
/home/kmahan/.virtualenvs/mf2py/local/lib/python2.7/site-packages/bs4/dammit.py:283: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif data[:4] == b'\xff\xfe\x00\x00':

```

**Comment by kylewm** [comment]
actually I don't quite understand why we need the UnicodeDammit calls; shouldn't BeautifulSoup be using it internally/giving us back utf-8 all the time?

**Comment by kevinmarks** [comment]
I wasn't seeing that from beautiful soup - is there  a config we set to
make it so?

**Comment by kylewm** [comment]
I merged your PR locally, and am testing it here. Using mf2py with html5lib, tested with Python 2.7 and 3.4.

I'm seeing the same number of failures (58 with py2.7) with and without the `unmung` call. Calling it adds those cryptic warning messages and a lot of repetition in the code, so I'd like to avoid it if it's not buying us anything.

Here's what I meant about BeautifulSoup, from http://www.crummy.com/software/BeautifulSoup/bs4/doc/#output-encoding

> When you write out a document from Beautiful Soup, you get a UTF-8 document, even if the document wasn’t in UTF-8 to begin with. 

Am I missing something? :confused:

**Comment by kylewm** [comment]
Determined that BS4 gives back byte strings when using lxml, where we want unicode everywhere.

So in my merged code I'll switch it to use `unicode(s)` (well, indirectly, since I have to alias it for py3-compat) instead of UnicodeDammit before checking in these changes.

**Pull request merged**
