### PR TITLE
Convert all string literals to unicode literals

### LINKED ISSUE #43: unicode everywhere
right now parsing gives a mix of unicode strings and byte strings

```
{'rels': {}, 'items': [{'type': [u'h-entry'], 'properties': {'name': [u'Example Author Home\n        Example Post'], u'in-reply-to': [{'type': [u'h-cite'], 'properties': {u'url': [u'http://example.com/post'], u'name': [u'Example Post'], u'author': [{'type': [u'h-card'], 'properties': {u'url': [u'http://example.com'], u'name': [u'Example Author']}, 'value': u'Example Author'}]}, 'value': u'http://example.com/post'}]}}], 'rel-urls': {}}
```

We should endeavor to make all keys and values unicode strings.

### PR DESCRIPTION
**Pull request by kylewm**
For consistency across all properties and values.

@tommorris @kevinmarks @kartikprabhu @snarfed do y'all agree that this is a good idea?

Fixes #43

### CODE REVIEW

**Comment by kevinmarks** [comment]
I think it is, otherwise we are leaving ascii conversion exceptions in there as a trap for users. We probably need test cases with complex unicode in.

**Comment by snarfed** [comment]
actually, if i understand this change right, i think it should be a noop. it's only changing string literals, not any character conversion or any other code, and python compares `str` to `unicode` correctly (e.g. `'asdf' == u'asdf'`), and hashes them equivalently too (e.g. `x['asdf'] == x[u'asdf']`)...so i _think_ this shouldn't cause any behavior changes?

also @kylewm, just fyi i think a less invasive way to do this is to add `from __future__ import unicode_literals` at the top. i don't feel strongly though.

**Comment by kylewm** [comment]
Interesting! 

So I think I was misled by the assert_equals output. When two dicts weren't otherwise equivalent, it would give me a diff that must have been based on the string output. because it would report things like 

```diff
>>> assert_equals({'letter': 'b', 'number': 1}, {'letter': u'b', 'number': 2})
AssertionError: {'number': 1, 'letter': 'b'} != {'number': 2, 'letter': u'b'}
- {'letter': 'b', 'number': 1}
?                           ^

+ {'letter': u'b', 'number': 2}
?            +               ^
```

making me think that 'b' != u'b', but if I fix the numbers, the letters work out.

**Comment by snarfed** [comment]
`webutil.testutil.assert_equals`? if so then yes, it converts to string to output differences nicely.

since i wrote that, though, the `unittest` module has added much nicer `assert*` methods and handling, including order-independence and nice diff output. (both python 2 and 3.) feel free to switch to those.

**Comment by kylewm** [comment]
this is `nose.tools.assert_equals`, which I think just maps to UnitTest.assertEquals

**Pull request merged**
